// <auto-generated />
using System;
using GNC_Rodrigues.BD.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GNC_Rodrigues.BD.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241001140110_reinicio")]
    partial class reinicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GNC_Rodrigues.BD.DATA.Entity.Cliente", b =>
                {
                    b.Property<string>("DNI")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DNI");

                    b.HasIndex(new[] { "DNI" }, "Cliente_UQ_DNI")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GNC_Rodrigues.BD.DATA.Entity.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AvisadoRetirar")
                        .HasColumnType("bit");

                    b.Property<string>("ClienteDNI")
                        .HasColumnType("nvarchar(12)");

                    b.Property<bool>("CortaCorriente")
                        .HasColumnType("bit");

                    b.Property<string>("Detalles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fallas")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FuncionaNafta")
                        .HasColumnType("bit");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PresupuestoConfirmado")
                        .HasColumnType("bit");

                    b.Property<string>("Reparacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VehiculoDominio")
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteDNI");

                    b.HasIndex("VehiculoDominio");

                    b.HasIndex(new[] { "Id" }, "Orden_UQ_Id")
                        .IsUnique();

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("GNC_Rodrigues.BD.DATA.Entity.Vehiculo", b =>
                {
                    b.Property<string>("Dominio")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ClienteDNI")
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Dominio");

                    b.HasIndex("ClienteDNI");

                    b.HasIndex(new[] { "Dominio" }, "Vehiculo_UQ_Dominio")
                        .IsUnique();

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("GNC_Rodrigues.BD.DATA.Entity.Orden", b =>
                {
                    b.HasOne("GNC_Rodrigues.BD.DATA.Entity.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteDNI");

                    b.HasOne("GNC_Rodrigues.BD.DATA.Entity.Vehiculo", "Vehiculo")
                        .WithMany("Ordenes")
                        .HasForeignKey("VehiculoDominio");

                    b.Navigation("Cliente");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("GNC_Rodrigues.BD.DATA.Entity.Vehiculo", b =>
                {
                    b.HasOne("GNC_Rodrigues.BD.DATA.Entity.Cliente", "Cliente")
                        .WithMany("vehiculos")
                        .HasForeignKey("ClienteDNI");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GNC_Rodrigues.BD.DATA.Entity.Cliente", b =>
                {
                    b.Navigation("vehiculos");
                });

            modelBuilder.Entity("GNC_Rodrigues.BD.DATA.Entity.Vehiculo", b =>
                {
                    b.Navigation("Ordenes");
                });
#pragma warning restore 612, 618
        }
    }
}
